config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :breweries, only: [:index, :show]
      resources :venues, only: [:index, :show]
      resources :beers, only: [:index, :show]
      resources :styles, only: [:index, :show]
    end
  end

  resources :venues, except: [:new, :show]
  resources :beers, except: [:new, :show]
  resources :breweries, except: [:new, :show]

  root 'breweries#index'
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  belongs_to :style
  validates :brewery, :brand, :style, presence: true

  def description
    #TODO - add style once the data is fixed
    brand
  end
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include FoursquareVenue

  has_many :beers

  def beer_descriptions
    beers.map(&:description).join(', ')
  end
end

app/models/concerns/foursquare_venue.rb
module FoursquareVenue
  extend ActiveSupport::Concern

  included do
    has_many :open_hours, as: :venue, dependent: :destroy
  end

  def grouped_open_hours
    open_hours.order(:day).group_by(&:day)
  end
end

app/models/foursquare_service.rb
module FoursquareService
  extend self

  def client
    @@client ||= Foursquare2::Client.new(
      client_id: Rails.application.secrets.foursquare_client_id,
      client_secret: Rails.application.secrets.foursquare_client_secret,
      api_version: '20150628'
    )
  end
end

app/models/open_hour.rb
class OpenHour < ActiveRecord::Base
  validates :day, :start, :end, :venue, presence: true
  belongs_to :venue, polymorphic: true

  def description
    description = "#{start.to_s(:time)} - #{self.end.to_s(:time)}"
    description += " (+)" if next_day
    description
  end
end

app/models/style.rb
class Style < ActiveRecord::Base
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable and :omniauthable
  # :recoverable, :registerable,
  devise :database_authenticatable, :rememberable,
         :trackable, :validatable, :lockable, :recoverable
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  include FoursquareVenue

  has_and_belongs_to_many :beers
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/api/v1/beers_controller.rb
class Api::V1::BeersController < ApplicationController
  def index
    @beers = Beer.all
    render json: @beers
  end

  def show
    @beer = Beer.find(params[:id])
    render json: @beer
  end
end

app/controllers/api/v1/breweries_controller.rb
class Api::V1::BreweriesController < ApplicationController
  def index
    @breweries = Brewery.all.includes(:beers, :open_hours)
    render json: @breweries
  end

  def show
    @brewery = Brewery.find(params[:id])
    render json: @brewery
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @posts = Post.all
    render json: @posts, status: :ok
  end

  def show
    @post = Post.find(params[:id])
    render json: @post, status: :ok
  end
end

app/controllers/api/v1/styles_controller.rb
class Api::V1::StylesController < ApplicationController
  respond_to :json
  def index
    @styles = Style.all
  end

  def show
    @style = Style.find(params[:id])
  end
end

app/controllers/api/v1/venues_controller.rb
class Api::V1::VenuesController < ApplicationController
  def index
    @venues = Venue.all.includes(:beers, :open_hours)
    render json: @venues
  end

  def show
    @venue = Venue.find(params[:id])
    render json: @venue
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :allow_cross_domain_access

  def allow_cross_domain_access
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end
end

app/controllers/beers_controller.rb
class BeersController < AdminController
  before_action :set_beer, only: [:edit, :update, :destroy]

  def index
    @beers = Beer.all.includes(:brewery).includes(:style).order('breweries.name')
    @beer = Beer.new
    @breweries = Brewery.all.order(:name)
    @styles = Style.all
  end

  def edit
    @breweries = Brewery.all.order(:name)
    @styles = Style.all
  end

  def create
    @beer = Beer.new(beer_params)
    respond_to do |format|
      if @beer.save
        format.html { redirect_to beers_url, notice: 'Beer was successfully created.' }
      else
        format.html do
          @beers = Beer.all
          render :index
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to edit_beer_url(@beer), notice: 'Beer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer
    @beer = Beer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_params
    params.require(:beer).permit(:brewery_id, :brand, :style_id, :color, :alcohol, :bitterness, :size, :draft)
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < AdminController
  before_action :set_brewery, only: [:edit, :update, :destroy]

  def index
    @breweries = Brewery.all
    @brewery = Brewery.new
  end

  def edit
  end

  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to breweries_url, notice: 'Brewery was successfully created.' }
      else
        format.html do
          @breweries = Brewery.all
          render :index
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to edit_brewery_url(@brewery), notice: 'Brewery was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :brewery_type, :email, :serves_people, :foursquare_id)
  end
end

app/controllers/venues_controller.rb
class VenuesController < AdminController
  before_action :set_venue, only: [:edit, :update, :destroy]

  def index
    @venues = Venue.all
    @venue = Venue.new
    @beers = Beer.all.includes(:brewery).order('breweries.name')
  end

  def edit
    @beers = Beer.all.includes(:brewery).order('breweries.name')
  end

  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to venues_url, notice: 'Venue was successfully created.' }
      else
        format.html do
          @venues = Venue.all
          render :index
       end
      end
    end
  end

  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to edit_venue_url(@venue), notice: 'Venue was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_venue
    @venue = Venue.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def venue_params
    params.require(:venue).permit(:name, :venue_type, :email, :foursquare_id, beer_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_tab_class(tab)
    'active' if controller_name == tab
  end
end

app/views/beers/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'shared/model_errors', model: @beer %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= form_for @beer do |f| %>
      <div class="form-group">
        <%= f.label :brewery_id %>
        <%= f.collection_select :brewery_id, @breweries, :id, :name, {}, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :brand %>
        <%= f.text_field :brand, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :style %>
        <%= f.collection_select :style_id, @styles, :id, :name, {}, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :color %>
        <%= f.text_field :color, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :alcohol %>
        <%= f.text_field :alcohol, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :bitterness %>
        <%= f.text_field :bitterness, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :size %>
        <%= f.text_field :size, class: 'form-control' %>
      </div>

      <div class="checkbox">
        <label>
          <%= f.check_box :draft %>Draft?
        </label>
      </div>

      <%= f.submit class: 'btn btn-success' %>
      <%= link_to 'Back', beers_url %>
    <% end %>
  </div>
</div>

app/views/beers/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t 'helpers.submit.update', model: Beer.model_name.human %></h1>
  </div>
</div>

<%= render 'form' %>

app/views/beers/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= Beer.model_name.human(count: 2) %></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-7">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th class="col-lg-4"><%= Beer.human_attribute_name('brand') %></th>
          <th class="col-lg-4"><%= Beer.human_attribute_name('style') %></th>
          <th class="col-lg-4"></th>
        </tr>
      </thead>

      <tbody>
        <% @beers.each do |beer| %>
          <tr>
            <td><%= beer.brand %></td>
            <td><%= beer.style.name if beer.style %></td>
            <td class="text-right">
              <%= link_to edit_beer_path(beer), class: 'btn btn-primary btn-circle' do %>
                <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
              <%= link_to beer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-circle' do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-lg-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t 'helpers.submit.create', model: Beer.model_name.human %></h3>
      </div>
      <div class="panel-body">
        <%= form_for @beer do |f| %>
          <%= render 'shared/model_errors', model: @beer %>
          <div class="form-group">
            <%= f.collection_select :brewery_id, @breweries, :id, :name, {}, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.text_field :brand, class: 'form-control', placeholder: Beer.human_attribute_name('brand') %>
          </div>

          <div class="form-group">
            <%= f.collection_select :style_id, @styles, :id, :name, {}, class: 'form-control', placeholder: Beer.human_attribute_name('style') %>
          </div>

          <div class="form-group">
            <%= f.text_field :color, class: 'form-control', placeholder: Beer.human_attribute_name('color') %>
          </div>

          <div class="form-group">
            <%= f.text_field :alcohol, class: 'form-control', placeholder: Beer.human_attribute_name('alcohol') %>
          </div>

          <div class="form-group">
            <%= f.text_field :bitterness, class: 'form-control', placeholder: Beer.human_attribute_name('bitterness') %>
          </div>

          <div class="form-group">
            <%= f.text_field :size, class: 'form-control', placeholder: Beer.human_attribute_name('size') %>
          </div>

          <div class="checkbox">
            <label>
              <%= f.check_box :draft %><%= Beer.human_attribute_name('draft') %>?
            </label>
          </div>

          <%= f.submit class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/breweries/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'shared/model_errors', model: @brewery %>
  </div>
</div>

<div class="row">
  <%= form_for @brewery do |f| %>
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :brewery_type %>
        <%= f.text_field :brewery_type, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :foursquare_id %>
        <%= f.text_field :foursquare_id, class: 'form-control', placeholder: "Foursquare (ID)" %>
      </div>

      <div class="checkbox">
        <label>
          <%= f.check_box :serves_people %>Serves people?
        </label>
      </div>

      <div class="form-group">
        <%= f.label :beers %>
        <p class="form-control-static"><%= @brewery.beer_descriptions %></p>
      </div>

      <%= f.submit class: 'btn btn-success' %>
      <%= link_to 'Back', breweries_url %>
    </div>

    <div class="col-lg-6">
      <%= render 'foursquare/info', model: @brewery %>
      <%= render 'foursquare/open_hours', model: @brewery %>
    </div>
  <% end %>
</div>

app/views/breweries/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t 'helpers.submit.update', model: Brewery.model_name.human %></h1>
  </div>
</div>

<%= render 'form' %>

app/views/breweries/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= Brewery.model_name.human(count: 2) %></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-7">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th class="col-lg-4"><%= Brewery.human_attribute_name('name') %></th>
          <th class="col-lg-4"><%= Brewery.human_attribute_name('foursquare_id') %></th>
          <th class="col-lg-4"></th>
        </tr>
      </thead>

      <tbody>
        <% @breweries.each do |brewery| %>
          <tr>
            <td><%= brewery.name %></td>
            <td><%= link_to brewery.foursquare_id, brewery.foursquare_url %></td>
            <td class="text-right">
              <%= link_to edit_brewery_path(brewery), class: 'btn btn-primary btn-circle' do %>
                <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
              <%= link_to brewery, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-circle' do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-lg-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t 'helpers.submit.create', model: Brewery.model_name.human %></h3>
      </div>
      <div class="panel-body">
        <%= form_for @brewery do |f| %>
          <%= render 'shared/model_errors', model: @brewery %>

          <div class="form-group">
            <%= f.text_field :name, class: 'form-control', placeholder: Brewery.human_attribute_name('name') %>
          </div>

          <div class="form-group">
            <%= f.text_field :brewery_type, class: 'form-control', placeholder: Brewery.human_attribute_name('brewery_type') %>
          </div>

          <div class="form-group">
            <%= f.email_field :email, class: 'form-control', placeholder: Brewery.human_attribute_name('email') %>
          </div>

          <div class="form-group">
            <%= f.text_field :foursquare_id, class: 'form-control', placeholder: Brewery.human_attribute_name('foursquare_id') %>
          </div>

          <div class="checkbox">
            <label>
              <%= f.check_box :serves_people %>Serves people?
            </label>
          </div>

          <%= f.submit class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/foursquare/_info.html.erb
<div class="panel panel-default foursquare">
  <div class="panel-heading">
    <h3 class="panel-title">Foursquare Info</h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt><%= model.class.human_attribute_name('department') %></dt>
      <dd><%= model.department %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><%= model.class.human_attribute_name('city') %></dt>
      <dd><%= model.city %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><%= model.class.human_attribute_name('address') %></dt>
      <dd><%= model.address %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><%= model.class.human_attribute_name('phone') %></dt>
      <dd><%= model.phone %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><%= model.class.human_attribute_name('web') %></dt>
      <dd><%= model.web %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><%= model.class.human_attribute_name('lat') %></dt>
      <dd><%= model.lat %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><%= model.class.human_attribute_name('lng') %></dt>
      <dd><%= model.lng %></dd>
    </dl>
  </div>
</div>

app/views/foursquare/_open_hours.html.erb
<div class="panel panel-default foursquare">
  <div class="panel-heading">
    <h3 class="panel-title"><%= model.class.human_attribute_name('open_hours') %></h3>
  </div>
  <div class="panel-body">
    <% model.grouped_open_hours.each do |day, hours| %>
      <dl class="dl-horizontal">
        <dt><%= I18n.t(:"date.day_names")[day] %></dt>
        <dd><%= hours.map(&:description).join(', ') %></dd>
      </dl>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top main-header">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'DondePinta Admin', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= navbar_tab_class('breweries') %>">
          <%= link_to 'Breweries', breweries_path %>
        </li>
        <li class="<%= navbar_tab_class('venues') %>">
          <%= link_to 'Venues', venues_path %>
        </li>
        <li class="<%= navbar_tab_class('beers') %>">
          <%= link_to 'Beers', beers_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href='#' class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.email %>
            <b class="caret"> </b>
          </a>
          <ul class="dropdown-menu">
            <li>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Birra</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' if user_signed_in? %>

  <div class="container">
    <%= content_tag :div, notice, class: 'alert alert-success' if notice %>
    <%= content_tag :div, alert, class: 'alert alert-danger' if alert %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_model_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <% model.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>

app/views/venues/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'shared/model_errors', model: @venue %>
  </div>
</div>

<div class="row">
  <%= form_for @venue do |f| %>
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :venue_type %>
        <%= f.text_field :venue_type, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :foursquare_id %>
        <%= f.text_field :foursquare_id, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :beer_ids %>
        <%= f.collection_select :beer_ids, @beers, :id, :description, {}, multiple: true,
          class: 'form-control' %>
      </div>

      <%= f.submit class: 'btn btn-success' %>
      <%= link_to 'Back', venues_url %>
    </div>

    <div class="col-lg-6">
      <%= render 'foursquare/info', model: @venue %>
      <%= render 'foursquare/open_hours', model: @venue %>
    </div>
  <% end %>
</div>

app/views/venues/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t 'helpers.submit.update', model: Venue.model_name.human %></h1>
  </div>
</div>

<%= render 'form' %>

app/views/venues/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= Venue.model_name.human(count: 2) %></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-7">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th class="col-lg-4"><%= Venue.human_attribute_name('name') %></th>
          <th class="col-lg-4"><%= Venue.human_attribute_name('foursquare_id') %></th>
          <th class="col-lg-4"></th>
        </tr>
      </thead>

      <tbody>
        <% @venues.each do |venue| %>
          <tr>
            <td><%= venue.name %></td>
            <td><%= link_to venue.foursquare_id, venue.foursquare_url %></td>
            <td class="text-right">
              <%= link_to edit_venue_path(venue), class: 'btn btn-primary btn-circle' do %>
                <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
              <%= link_to venue, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-circle' do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-lg-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t 'helpers.submit.create', model: Venue.model_name.human %></h3>
      </div>
      <div class="panel-body">
        <%= form_for @venue do |f| %>
          <%= render 'shared/model_errors', model: @venue %>

          <div class="form-group">
            <%= f.text_field :name, class: 'form-control', placeholder: Venue.human_attribute_name('name') %>
          </div>

          <div class="form-group">
            <%= f.text_field :venue_type, class: 'form-control', placeholder: Venue.human_attribute_name('venue_type') %>
          </div>

          <div class="form-group">
            <%= f.email_field :email, class: 'form-control', placeholder: Venue.human_attribute_name('email') %>
          </div>

          <div class="form-group">
            <%= f.text_field :foursquare_id, class: 'form-control', placeholder: Venue.human_attribute_name('foursquare_id') %>
          </div>

          <div class="form-group">
            <%= f.collection_select :beer_ids, @beers, :id, :description, {}, class: 'form-control',
              multiple: true %>
          </div>

          <%= f.submit class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>